steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t europe-north1-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA} \
                     -t europe-north1-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:latest \
                     --build-arg NEXT_PUBLIC_SERVER_URL=${_NEXT_PUBLIC_SERVER_URL} \
                     .

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push europe-north1-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA}
        docker push europe-north1-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:latest

  # 3. Deploy to Cloud Run (Update existing service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Determine service name and environment based on project and trigger
        if [ "${PROJECT_ID}" = "the-white-prod" ]; then
          # Production project - only deploy on tag creation
          SERVICE_NAME="fashion-web"
          ENVIRONMENT="PRODUCTION"

          # Verify this is a tag-based deployment
          if [ -n "$TAG_NAME" ]; then
            echo "🏷️  Tag-based deployment to PRODUCTION: $TAG_NAME"
          else
            echo "⚠️  Production deployments require a version tag (e.g., v1.0.0)"
            echo "⚠️  Skipping deployment..."
            exit 0
          fi

        elif [ "${PROJECT_ID}" = "the-white-dev" ]; then
          # Dev project - deploy on PR to main or manual trigger
          SERVICE_NAME="fashion-web-dev"
          ENVIRONMENT="DEV"

          # Log the trigger type
          if [ -n "${_PR_NUMBER:-}" ]; then
            echo "🔀 PR deployment to DEV: PR #${_PR_NUMBER} targeting main branch"
          elif [ -n "${BRANCH_NAME:-}" ]; then
            echo "🌿 Branch deployment to DEV: ${BRANCH_NAME}"
          else
            echo "ℹ️  Manual deployment to DEV"
          fi

        else
          echo "⚠️  Unknown project ${PROJECT_ID}. Skipping deployment..."
          exit 0
        fi

        echo "🚀 Deploying ${SHORT_SHA} to $ENVIRONMENT environment ($SERVICE_NAME) in ${PROJECT_ID}..."

        # Only update the image, preserve all other Terraform-managed settings
        gcloud run services update $SERVICE_NAME \
          --image europe-north1-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA} \
          --region europe-north1 \
          --project ${PROJECT_ID} \
          --quiet

        echo "✅ Deployment complete!"
        echo "📊 Service URL: https://$SERVICE_NAME-$(gcloud run services describe $SERVICE_NAME --region=europe-north1 --project=${PROJECT_ID} --format='value(status.url)' | cut -d'/' -f3)"

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_SERVER_URL: '' # Must be provided by trigger or CLI
