steps:
  # 0. Cancel previous builds for the same branch/commit
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🛑 Canceling previous builds for this branch..."

        # Get current build ID and branch
        CURRENT_BUILD_ID="${BUILD_ID}"
        BRANCH_NAME="${BRANCH_NAME:-${TAG_NAME:-main}}"

        echo "Current build: $${CURRENT_BUILD_ID}"
        echo "Branch/Tag: $${BRANCH_NAME}"

        # List all running builds for this project and region
        RUNNING_BUILDS=$(gcloud builds list \
          --region=${_REGION} \
          --project=${PROJECT_ID} \
          --filter="status=WORKING OR status=QUEUED" \
          --format="value(id)" \
          --limit=50 2>/dev/null || echo "")

        if [ -n "$$RUNNING_BUILDS" ]; then
          echo "Found running/queued builds:"
          echo "$$RUNNING_BUILDS"
          
          # Cancel each build except the current one
          for BUILD_ID in $$RUNNING_BUILDS; do
            if [ "$$BUILD_ID" != "$$CURRENT_BUILD_ID" ]; then
              echo "Canceling build: $${BUILD_ID}"
              gcloud builds cancel "$$BUILD_ID" \
                --region=${_REGION} \
                --project=${PROJECT_ID} \
                --quiet 2>/dev/null || echo "Failed to cancel $${BUILD_ID} (may have already finished)"
            fi
          done
          echo "✅ Previous builds canceled"
        else
          echo "ℹ️  No previous builds to cancel"
        fi

  # 1. Fetch secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Determine secret names based on project
        if [ "${PROJECT_ID}" = "the-white-prod-481217" ]; then
          PAYLOAD_SECRET_NAME="PAYLOAD_SECRET"
          DATABASE_URI_NAME="DATABASE_URI"
        elif [ "${PROJECT_ID}" = "the-white-dev-481217" ]; then
          PAYLOAD_SECRET_NAME="PAYLOAD_SECRET_DEV"
          DATABASE_URI_NAME="DATABASE_URI_DEV"
        else
          PAYLOAD_SECRET_NAME="PAYLOAD_SECRET"
          DATABASE_URI_NAME="DATABASE_URI"
        fi

        # Get secrets from Secret Manager
        echo "🔐 Fetching secrets from Secret Manager..."
        echo "   Project: ${PROJECT_ID}"
        echo "   Looking for: $$PAYLOAD_SECRET_NAME"

        # Try to fetch PAYLOAD_SECRET - show error if it fails
        PAYLOAD_SECRET_OUTPUT=$$(gcloud secrets versions access latest --secret=$$PAYLOAD_SECRET_NAME --project=${PROJECT_ID} 2>&1)
        PAYLOAD_SECRET_EXIT=$$?

        if [ $$PAYLOAD_SECRET_EXIT -eq 0 ]; then
          PAYLOAD_SECRET="$$PAYLOAD_SECRET_OUTPUT"
          if [ -n "$$PAYLOAD_SECRET" ]; then
            PAYLOAD_SECRET_LEN=$${#PAYLOAD_SECRET}
            echo "✅ PAYLOAD_SECRET fetched successfully ($$PAYLOAD_SECRET_LEN chars)"
            # Write to file for next step
            echo -n "$$PAYLOAD_SECRET" > /workspace/payload_secret.txt
          else
            echo "❌ ERROR: PAYLOAD_SECRET is empty!"
            exit 1
          fi
        else
          echo "❌ ERROR: Failed to fetch PAYLOAD_SECRET:"
          echo "$$PAYLOAD_SECRET_OUTPUT"
          echo ""
          echo "Possible issues:"
          echo "  1. Secret '$$PAYLOAD_SECRET_NAME' doesn't exist in ${PROJECT_ID}"
          echo "  2. Cloud Build service account lacks permission"
          echo "  3. Secret name is incorrect"
          exit 1
        fi

        # DATABASE_URI is optional for build
        DATABASE_URI=$$(gcloud secrets versions access latest --secret=$$DATABASE_URI_NAME --project=${PROJECT_ID} 2>/dev/null || echo "")
        if [ -n "$$DATABASE_URI" ]; then
          echo "✅ DATABASE_URI fetched successfully"
          echo -n "$$DATABASE_URI" > /workspace/database_uri.txt
        else
          echo "⚠️  DATABASE_URI not found (optional for build)"
          echo -n "" > /workspace/database_uri.txt
        fi

  # 2. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Read secrets from files created in previous step
        PAYLOAD_SECRET=$$(cat /workspace/payload_secret.txt)
        DATABASE_URI=$$(cat /workspace/database_uri.txt)

        echo "🔨 Building Docker image..."
        echo "   PAYLOAD_SECRET length: $${#PAYLOAD_SECRET} chars"
        echo "   DATABASE_URI length: $${#DATABASE_URI} chars"

        # Enable BuildKit for faster builds with cache mounts
        export DOCKER_BUILDKIT=1
        export BUILDKIT_PROGRESS=plain

        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA} \
                     -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:latest \
                     --build-arg NEXT_PUBLIC_SERVER_URL=${_NEXT_PUBLIC_SERVER_URL} \
                     --build-arg PAYLOAD_SECRET="$$PAYLOAD_SECRET" \
                     --build-arg DATABASE_URI="$$DATABASE_URI" \
                     --cache-from ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:latest \
                     .

  # 3. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:latest

  # 4. Deploy to Cloud Run (Update existing service)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Determine service name and environment based on project and trigger
        if [ "${PROJECT_ID}" = "the-white-prod-481217" ]; then
          # Production project - only deploy on tag creation
          service_name="fashion-web"

          # Verify this is a tag-based deployment
          if [ -n "${TAG_NAME}" ]; then
            echo "🏷️  Tag-based deployment to PRODUCTION: ${TAG_NAME}"
          else
            echo "⚠️  Production deployments require a version tag (e.g., v1.0.0)"
            echo "⚠️  Skipping deployment..."
            exit 0
          fi

        elif [ "${PROJECT_ID}" = "the-white-dev-481217" ]; then
          # Dev project - deploy on PR to main or manual trigger
          service_name="fashion-web-dev"

          # Log the trigger type
          if [ -n "${_PR_NUMBER:-}" ]; then
            echo "🔀 PR deployment to DEV: PR #${_PR_NUMBER} targeting main branch"
          elif [ -n "${BRANCH_NAME:-}" ]; then
            echo "🌿 Branch deployment to DEV: ${BRANCH_NAME}"
          else
            echo "ℹ️  Manual deployment to DEV"
          fi

        else
          echo "⚠️  Unknown project ${PROJECT_ID}. Skipping deployment..."
          exit 0
        fi

        echo "🚀 Deploying ${SHORT_SHA} to $$service_name in ${PROJECT_ID}..."

        # Only update the image, preserve all other Terraform-managed settings
        gcloud run services update $$service_name \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/app-images/fashion-web:${SHORT_SHA} \
          --region ${_REGION} \
          --project ${PROJECT_ID} \
          --quiet

        echo "✅ Deployment complete!"
        SERVICE_URL=$$(gcloud run services describe $$service_name --region=${_REGION} --project=${PROJECT_ID} --format='value(status.url)' | cut -d'/' -f3)
        echo "📊 Service URL: https://$$SERVICE_URL"

timeout: 1800s

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_SERVER_URL: '' # Must be provided by trigger or CLI
  _REGION: 'asia-southeast1' # Singapore - closest to Vietnam
