import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // Back-fill referral_code for users created before the beforeChange
  // hook that auto-generates it. The WHERE clause makes this idempotent —
  // rows already containing a code are untouched.
  await db.execute(sql`
    UPDATE users
    SET referral_code = 'TW-' || upper(substr(md5(random()::text || id::text), 1, 10))
    WHERE referral_code IS NULL;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  // No-op: we cannot distinguish back-filled codes from codes that were
  // legitimately generated by the beforeChange hook.
}
