/**
 * Populate `sizeChart` on existing products without re-uploading any images or
 * touching other fields. Reads the chart templates from `productSeedData` in
 * `src/endpoints/seed/products.ts` and upserts VI + EN locales per slug.
 *
 * Usage: `pnpm tsx scripts/seed-size-charts.ts`
 */
import { existsSync, readFileSync } from 'fs'
import path from 'path'

function loadEnvFile(file: string): void {
  if (!existsSync(file)) return
  for (const raw of readFileSync(file, 'utf-8').split('\n')) {
    const line = raw.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq < 0) continue
    const key = line.slice(0, eq).trim()
    let value = line.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    if (process.env[key] === undefined) process.env[key] = value
  }
}

const cwd = process.cwd()
loadEnvFile(path.join(cwd, '.env.local'))
loadEnvFile(path.join(cwd, '.env'))

async function main() {
  const { getPayload } = await import('payload')
  const { default: config } = await import('@payload-config')
  const { productSeedData } = await import('@/endpoints/seed/products')

  const payload = await getPayload({ config })

  let updated = 0
  let skipped = 0

  for (const product of productSeedData) {
    if (!product.sizeChart) {
      payload.logger.info(`— ${product.slug}: no chart template, skipping`)
      skipped++
      continue
    }

    const found = await payload.find({
      collection: 'products',
      where: { slug: { equals: product.slug } },
      depth: 0,
      locale: 'vi',
    })

    const existing = found.docs[0]
    if (!existing) {
      payload.logger.warn(`  ⚠ product not found by slug: ${product.slug}`)
      continue
    }

    // VI upsert — set columns, rows (full replace), note.
    const sizeChartVi = {
      columns: product.sizeChart.columns.map((c) => ({ header: c.headerVi })),
      rows: product.sizeChart.rows.map((cells) => ({
        cells: cells.map((value) => ({ value })),
      })),
      note: product.sizeChart.noteVi,
    }

    const viDoc = await payload.update({
      collection: 'products',
      id: existing.id,
      locale: 'vi',
      data: { sizeChart: sizeChartVi as never },
    })
    payload.logger.info(`  ✓ ${product.slug} (vi) updated`)

    // EN upsert — use the column IDs generated by the VI write so Payload
    // updates the EN header in place instead of replacing the array.
    const createdColumns = ((viDoc as any).sizeChart?.columns || []) as Array<{ id: string }>
    const sizeChartEn = {
      columns: product.sizeChart.columns.map((c, i) => ({
        id: createdColumns[i]?.id,
        header: c.headerEn,
      })),
      note: product.sizeChart.noteEn,
    }

    await payload.update({
      collection: 'products',
      id: existing.id,
      locale: 'en',
      data: { sizeChart: sizeChartEn as never },
    })
    payload.logger.info(`  ✓ ${product.slug} (en) updated`)
    updated++
  }

  payload.logger.info(`✅ Done. ${updated} updated, ${skipped} skipped.`)
  process.exit(0)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
